### PR TITLE
Move defer after error check

### PR DESCRIPTION
**Pull request by morelena**
Otherwise, there will be panic

Signed-off-by: Elena Morozova <lelenanam@gmail.com>

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-4** [comment]
@morelena updated the pull request - [view changes](https://github.com/facebookincubator/dhcplb/pull/10/files/d66a696bd68b8f5dfb2acd3bbc7d873a5f69cee6..332ec6b8ed155efff44823e8e8443a6bcc534efc)

**Comment by mkaczanowski** [comment]
Thanks!
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3910847).

**Pull request closed without merging**
